# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-27 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today, unique=True, verbose_name='Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('seconds', models.BigIntegerField(default=0, editable=False, verbose_name='Seconds')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='Is weekend')),
            ],
            options={
                'verbose_name': 'Work date',
                'verbose_name_plural': 'Work dates',
            },
        ),
    ]
